# Generated by Django 3.2.6 on 2021-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20210816_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='skill',
        ),
        migrations.AddField(
            model_name='projects',
            name='skill',
            field=models.ManyToManyField(related_name='skill', to='portfolio_app.Skill'),
        ),
    ]
